/*
NetHSM

All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnattendedBootConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnattendedBootConfig{}

// UnattendedBootConfig struct for UnattendedBootConfig
type UnattendedBootConfig struct {
	Status Switch `json:"status"`
}

type _UnattendedBootConfig UnattendedBootConfig

// NewUnattendedBootConfig instantiates a new UnattendedBootConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnattendedBootConfig(status Switch) *UnattendedBootConfig {
	this := UnattendedBootConfig{}
	this.Status = status
	return &this
}

// NewUnattendedBootConfigWithDefaults instantiates a new UnattendedBootConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnattendedBootConfigWithDefaults() *UnattendedBootConfig {
	this := UnattendedBootConfig{}
	return &this
}

// GetStatus returns the Status field value
func (o *UnattendedBootConfig) GetStatus() Switch {
	if o == nil {
		var ret Switch
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UnattendedBootConfig) GetStatusOk() (*Switch, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UnattendedBootConfig) SetStatus(v Switch) {
	o.Status = v
}

func (o UnattendedBootConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnattendedBootConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UnattendedBootConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnattendedBootConfig := _UnattendedBootConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnattendedBootConfig)

	if err != nil {
		return err
	}

	*o = UnattendedBootConfig(varUnattendedBootConfig)

	return err
}

type NullableUnattendedBootConfig struct {
	value *UnattendedBootConfig
	isSet bool
}

func (v NullableUnattendedBootConfig) Get() *UnattendedBootConfig {
	return v.value
}

func (v *NullableUnattendedBootConfig) Set(val *UnattendedBootConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUnattendedBootConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUnattendedBootConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnattendedBootConfig(val *UnattendedBootConfig) *NullableUnattendedBootConfig {
	return &NullableUnattendedBootConfig{value: val, isSet: true}
}

func (v NullableUnattendedBootConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnattendedBootConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


