/*
NetHSM

All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrivateKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateKey{}

// PrivateKey struct for PrivateKey
type PrivateKey struct {
	Mechanisms []KeyMechanism `json:"mechanisms"`
	Type KeyType `json:"type"`
	Private KeyPrivateData `json:"private"`
	Restrictions *KeyRestrictions `json:"restrictions,omitempty"`
}

type _PrivateKey PrivateKey

// NewPrivateKey instantiates a new PrivateKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateKey(mechanisms []KeyMechanism, type_ KeyType, private KeyPrivateData) *PrivateKey {
	this := PrivateKey{}
	this.Mechanisms = mechanisms
	this.Type = type_
	this.Private = private
	return &this
}

// NewPrivateKeyWithDefaults instantiates a new PrivateKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateKeyWithDefaults() *PrivateKey {
	this := PrivateKey{}
	return &this
}

// GetMechanisms returns the Mechanisms field value
func (o *PrivateKey) GetMechanisms() []KeyMechanism {
	if o == nil {
		var ret []KeyMechanism
		return ret
	}

	return o.Mechanisms
}

// GetMechanismsOk returns a tuple with the Mechanisms field value
// and a boolean to check if the value has been set.
func (o *PrivateKey) GetMechanismsOk() ([]KeyMechanism, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mechanisms, true
}

// SetMechanisms sets field value
func (o *PrivateKey) SetMechanisms(v []KeyMechanism) {
	o.Mechanisms = v
}

// GetType returns the Type field value
func (o *PrivateKey) GetType() KeyType {
	if o == nil {
		var ret KeyType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PrivateKey) GetTypeOk() (*KeyType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PrivateKey) SetType(v KeyType) {
	o.Type = v
}

// GetPrivate returns the Private field value
func (o *PrivateKey) GetPrivate() KeyPrivateData {
	if o == nil {
		var ret KeyPrivateData
		return ret
	}

	return o.Private
}

// GetPrivateOk returns a tuple with the Private field value
// and a boolean to check if the value has been set.
func (o *PrivateKey) GetPrivateOk() (*KeyPrivateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Private, true
}

// SetPrivate sets field value
func (o *PrivateKey) SetPrivate(v KeyPrivateData) {
	o.Private = v
}

// GetRestrictions returns the Restrictions field value if set, zero value otherwise.
func (o *PrivateKey) GetRestrictions() KeyRestrictions {
	if o == nil || IsNil(o.Restrictions) {
		var ret KeyRestrictions
		return ret
	}
	return *o.Restrictions
}

// GetRestrictionsOk returns a tuple with the Restrictions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateKey) GetRestrictionsOk() (*KeyRestrictions, bool) {
	if o == nil || IsNil(o.Restrictions) {
		return nil, false
	}
	return o.Restrictions, true
}

// HasRestrictions returns a boolean if a field has been set.
func (o *PrivateKey) HasRestrictions() bool {
	if o != nil && !IsNil(o.Restrictions) {
		return true
	}

	return false
}

// SetRestrictions gets a reference to the given KeyRestrictions and assigns it to the Restrictions field.
func (o *PrivateKey) SetRestrictions(v KeyRestrictions) {
	o.Restrictions = &v
}

func (o PrivateKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mechanisms"] = o.Mechanisms
	toSerialize["type"] = o.Type
	toSerialize["private"] = o.Private
	if !IsNil(o.Restrictions) {
		toSerialize["restrictions"] = o.Restrictions
	}
	return toSerialize, nil
}

func (o *PrivateKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mechanisms",
		"type",
		"private",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivateKey := _PrivateKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrivateKey)

	if err != nil {
		return err
	}

	*o = PrivateKey(varPrivateKey)

	return err
}

type NullablePrivateKey struct {
	value *PrivateKey
	isSet bool
}

func (v NullablePrivateKey) Get() *PrivateKey {
	return v.value
}

func (v *NullablePrivateKey) Set(val *PrivateKey) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateKey) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateKey(val *PrivateKey) *NullablePrivateKey {
	return &NullablePrivateKey{value: val, isSet: true}
}

func (v NullablePrivateKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


