/*
NetHSM

All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnlockPassphraseConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnlockPassphraseConfig{}

// UnlockPassphraseConfig struct for UnlockPassphraseConfig
type UnlockPassphraseConfig struct {
	NewPassphrase string `json:"newPassphrase"`
	CurrentPassphrase string `json:"currentPassphrase"`
}

type _UnlockPassphraseConfig UnlockPassphraseConfig

// NewUnlockPassphraseConfig instantiates a new UnlockPassphraseConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnlockPassphraseConfig(newPassphrase string, currentPassphrase string) *UnlockPassphraseConfig {
	this := UnlockPassphraseConfig{}
	this.NewPassphrase = newPassphrase
	this.CurrentPassphrase = currentPassphrase
	return &this
}

// NewUnlockPassphraseConfigWithDefaults instantiates a new UnlockPassphraseConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnlockPassphraseConfigWithDefaults() *UnlockPassphraseConfig {
	this := UnlockPassphraseConfig{}
	return &this
}

// GetNewPassphrase returns the NewPassphrase field value
func (o *UnlockPassphraseConfig) GetNewPassphrase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewPassphrase
}

// GetNewPassphraseOk returns a tuple with the NewPassphrase field value
// and a boolean to check if the value has been set.
func (o *UnlockPassphraseConfig) GetNewPassphraseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewPassphrase, true
}

// SetNewPassphrase sets field value
func (o *UnlockPassphraseConfig) SetNewPassphrase(v string) {
	o.NewPassphrase = v
}

// GetCurrentPassphrase returns the CurrentPassphrase field value
func (o *UnlockPassphraseConfig) GetCurrentPassphrase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentPassphrase
}

// GetCurrentPassphraseOk returns a tuple with the CurrentPassphrase field value
// and a boolean to check if the value has been set.
func (o *UnlockPassphraseConfig) GetCurrentPassphraseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPassphrase, true
}

// SetCurrentPassphrase sets field value
func (o *UnlockPassphraseConfig) SetCurrentPassphrase(v string) {
	o.CurrentPassphrase = v
}

func (o UnlockPassphraseConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnlockPassphraseConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["newPassphrase"] = o.NewPassphrase
	toSerialize["currentPassphrase"] = o.CurrentPassphrase
	return toSerialize, nil
}

func (o *UnlockPassphraseConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"newPassphrase",
		"currentPassphrase",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnlockPassphraseConfig := _UnlockPassphraseConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnlockPassphraseConfig)

	if err != nil {
		return err
	}

	*o = UnlockPassphraseConfig(varUnlockPassphraseConfig)

	return err
}

type NullableUnlockPassphraseConfig struct {
	value *UnlockPassphraseConfig
	isSet bool
}

func (v NullableUnlockPassphraseConfig) Get() *UnlockPassphraseConfig {
	return v.value
}

func (v *NullableUnlockPassphraseConfig) Set(val *UnlockPassphraseConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUnlockPassphraseConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUnlockPassphraseConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnlockPassphraseConfig(val *UnlockPassphraseConfig) *NullableUnlockPassphraseConfig {
	return &NullableUnlockPassphraseConfig{value: val, isSet: true}
}

func (v NullableUnlockPassphraseConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnlockPassphraseConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


