/*
NetHSM

All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NamespaceItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NamespaceItem{}

// NamespaceItem struct for NamespaceItem
type NamespaceItem struct {
	Id string `json:"id" validate:"regexp=^[a-zA-Z0-9]+$"`
}

type _NamespaceItem NamespaceItem

// NewNamespaceItem instantiates a new NamespaceItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceItem(id string) *NamespaceItem {
	this := NamespaceItem{}
	this.Id = id
	return &this
}

// NewNamespaceItemWithDefaults instantiates a new NamespaceItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceItemWithDefaults() *NamespaceItem {
	this := NamespaceItem{}
	return &this
}

// GetId returns the Id field value
func (o *NamespaceItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NamespaceItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NamespaceItem) SetId(v string) {
	o.Id = v
}

func (o NamespaceItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NamespaceItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *NamespaceItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNamespaceItem := _NamespaceItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNamespaceItem)

	if err != nil {
		return err
	}

	*o = NamespaceItem(varNamespaceItem)

	return err
}

type NullableNamespaceItem struct {
	value *NamespaceItem
	isSet bool
}

func (v NullableNamespaceItem) Get() *NamespaceItem {
	return v.value
}

func (v *NullableNamespaceItem) Set(val *NamespaceItem) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceItem) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceItem(val *NamespaceItem) *NullableNamespaceItem {
	return &NullableNamespaceItem{value: val, isSet: true}
}

func (v NullableNamespaceItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


