/*
NetHSM

All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HealthStateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthStateData{}

// HealthStateData struct for HealthStateData
type HealthStateData struct {
	State SystemState `json:"state"`
}

type _HealthStateData HealthStateData

// NewHealthStateData instantiates a new HealthStateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthStateData(state SystemState) *HealthStateData {
	this := HealthStateData{}
	this.State = state
	return &this
}

// NewHealthStateDataWithDefaults instantiates a new HealthStateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthStateDataWithDefaults() *HealthStateData {
	this := HealthStateData{}
	return &this
}

// GetState returns the State field value
func (o *HealthStateData) GetState() SystemState {
	if o == nil {
		var ret SystemState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *HealthStateData) GetStateOk() (*SystemState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *HealthStateData) SetState(v SystemState) {
	o.State = v
}

func (o HealthStateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthStateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *HealthStateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthStateData := _HealthStateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthStateData)

	if err != nil {
		return err
	}

	*o = HealthStateData(varHealthStateData)

	return err
}

type NullableHealthStateData struct {
	value *HealthStateData
	isSet bool
}

func (v NullableHealthStateData) Get() *HealthStateData {
	return v.value
}

func (v *NullableHealthStateData) Set(val *HealthStateData) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthStateData) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthStateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthStateData(val *HealthStateData) *NullableHealthStateData {
	return &NullableHealthStateData{value: val, isSet: true}
}

func (v NullableHealthStateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthStateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


