/*
NetHSM

All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserItem{}

// UserItem struct for UserItem
type UserItem struct {
	User string `json:"user" validate:"regexp=^([a-zA-Z0-9][a-zA-Z0-9_.-]*~)?[a-zA-Z0-9][a-zA-Z0-9_.-]*$"`
}

type _UserItem UserItem

// NewUserItem instantiates a new UserItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserItem(user string) *UserItem {
	this := UserItem{}
	this.User = user
	return &this
}

// NewUserItemWithDefaults instantiates a new UserItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserItemWithDefaults() *UserItem {
	this := UserItem{}
	return &this
}

// GetUser returns the User field value
func (o *UserItem) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *UserItem) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *UserItem) SetUser(v string) {
	o.User = v
}

func (o UserItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *UserItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserItem := _UserItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserItem)

	if err != nil {
		return err
	}

	*o = UserItem(varUserItem)

	return err
}

type NullableUserItem struct {
	value *UserItem
	isSet bool
}

func (v NullableUserItem) Get() *UserItem {
	return v.value
}

func (v *NullableUserItem) Set(val *UserItem) {
	v.value = val
	v.isSet = true
}

func (v NullableUserItem) IsSet() bool {
	return v.isSet
}

func (v *NullableUserItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserItem(val *UserItem) *NullableUserItem {
	return &NullableUserItem{value: val, isSet: true}
}

func (v NullableUserItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


