/*
NetHSM

All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the KeyPrivateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyPrivateData{}

// KeyPrivateData struct for KeyPrivateData
type KeyPrivateData struct {
	PrimeP *string `json:"primeP,omitempty" validate:"regexp=^[a-zA-Z0-9+\\/]+={0,3}$"`
	PrimeQ *string `json:"primeQ,omitempty" validate:"regexp=^[a-zA-Z0-9+\\/]+={0,3}$"`
	PublicExponent *string `json:"publicExponent,omitempty" validate:"regexp=^[a-zA-Z0-9+\\/]+={0,3}$"`
	Data *string `json:"data,omitempty" validate:"regexp=^[a-zA-Z0-9+\\/]+={0,3}$"`
}

// NewKeyPrivateData instantiates a new KeyPrivateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyPrivateData() *KeyPrivateData {
	this := KeyPrivateData{}
	return &this
}

// NewKeyPrivateDataWithDefaults instantiates a new KeyPrivateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyPrivateDataWithDefaults() *KeyPrivateData {
	this := KeyPrivateData{}
	return &this
}

// GetPrimeP returns the PrimeP field value if set, zero value otherwise.
func (o *KeyPrivateData) GetPrimeP() string {
	if o == nil || IsNil(o.PrimeP) {
		var ret string
		return ret
	}
	return *o.PrimeP
}

// GetPrimePOk returns a tuple with the PrimeP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyPrivateData) GetPrimePOk() (*string, bool) {
	if o == nil || IsNil(o.PrimeP) {
		return nil, false
	}
	return o.PrimeP, true
}

// HasPrimeP returns a boolean if a field has been set.
func (o *KeyPrivateData) HasPrimeP() bool {
	if o != nil && !IsNil(o.PrimeP) {
		return true
	}

	return false
}

// SetPrimeP gets a reference to the given string and assigns it to the PrimeP field.
func (o *KeyPrivateData) SetPrimeP(v string) {
	o.PrimeP = &v
}

// GetPrimeQ returns the PrimeQ field value if set, zero value otherwise.
func (o *KeyPrivateData) GetPrimeQ() string {
	if o == nil || IsNil(o.PrimeQ) {
		var ret string
		return ret
	}
	return *o.PrimeQ
}

// GetPrimeQOk returns a tuple with the PrimeQ field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyPrivateData) GetPrimeQOk() (*string, bool) {
	if o == nil || IsNil(o.PrimeQ) {
		return nil, false
	}
	return o.PrimeQ, true
}

// HasPrimeQ returns a boolean if a field has been set.
func (o *KeyPrivateData) HasPrimeQ() bool {
	if o != nil && !IsNil(o.PrimeQ) {
		return true
	}

	return false
}

// SetPrimeQ gets a reference to the given string and assigns it to the PrimeQ field.
func (o *KeyPrivateData) SetPrimeQ(v string) {
	o.PrimeQ = &v
}

// GetPublicExponent returns the PublicExponent field value if set, zero value otherwise.
func (o *KeyPrivateData) GetPublicExponent() string {
	if o == nil || IsNil(o.PublicExponent) {
		var ret string
		return ret
	}
	return *o.PublicExponent
}

// GetPublicExponentOk returns a tuple with the PublicExponent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyPrivateData) GetPublicExponentOk() (*string, bool) {
	if o == nil || IsNil(o.PublicExponent) {
		return nil, false
	}
	return o.PublicExponent, true
}

// HasPublicExponent returns a boolean if a field has been set.
func (o *KeyPrivateData) HasPublicExponent() bool {
	if o != nil && !IsNil(o.PublicExponent) {
		return true
	}

	return false
}

// SetPublicExponent gets a reference to the given string and assigns it to the PublicExponent field.
func (o *KeyPrivateData) SetPublicExponent(v string) {
	o.PublicExponent = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *KeyPrivateData) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyPrivateData) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *KeyPrivateData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *KeyPrivateData) SetData(v string) {
	o.Data = &v
}

func (o KeyPrivateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyPrivateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrimeP) {
		toSerialize["primeP"] = o.PrimeP
	}
	if !IsNil(o.PrimeQ) {
		toSerialize["primeQ"] = o.PrimeQ
	}
	if !IsNil(o.PublicExponent) {
		toSerialize["publicExponent"] = o.PublicExponent
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableKeyPrivateData struct {
	value *KeyPrivateData
	isSet bool
}

func (v NullableKeyPrivateData) Get() *KeyPrivateData {
	return v.value
}

func (v *NullableKeyPrivateData) Set(val *KeyPrivateData) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyPrivateData) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyPrivateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyPrivateData(val *KeyPrivateData) *NullableKeyPrivateData {
	return &NullableKeyPrivateData{value: val, isSet: true}
}

func (v NullableKeyPrivateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyPrivateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


